DELIMITER //
DROP PROCEDURE IF EXISTS transational_distance;
CREATE PROCEDURE transational_distance
(
	IN base VARCHAR(30)
)
BEGIN
	SET @base = base;
	SET @view_alunos = 'alunos';
	SET @view_disciplinas = CONCAT(@base, '_disciplinas');
	SET @view_professores = 'professores';
	SET @view_base_log_reduzido = CONCAT(@base, '_base_log_reduzido');
	SET @view_dist_tran = CONCAT(@base, '_dist_tran');

	SET @drop_query = CONCAT(
		'DROP TABLE IF EXISTS ', @view_dist_tran, ';'
	);

	PREPARE stmt FROM @drop_query;
	EXECUTE stmt;
	DEALLOCATE PREPARE stmt;

	SET @query = CONCAT(
		' CREATE TABLE ', @view_dist_tran, ' AS ',
			' SELECT ' ,
			' ', @base,'.curso AS \'Curso\', ' ,
			' ', @base,'.semestre AS \'Semestre\', ',
			' ', @base,'.periodo AS \'Período\', ',
			' ', @base,'.disciplina_nome AS \'Nome da Disciplina\', ',
			' ', @base,'.disciplina_id AS \'ID da Disciplina\', ',
			' ', @base,'.data_inicio AS \'Data de Início\', ',
			' ', @base,'.data_fim AS \'Data de Final\', ' ,
			' ', @base,'.aluno_nome AS \'Nome do Aluno\', ',
			' ', @base,'.aluno_id AS \'ID do Aluno\', ',
			' ', @base,'.cpf AS \'CPF\', ',
			' IFNULL(VAR01.VAR01,0) AS \'VAR01\', ',
			' IFNULL(VAR04.VAR04,0) AS \'VAR04\', ',
			' IFNULL(VAR05.VAR05,0) AS \'VAR05\', ',
			' IFNULL(VAR08.VAR08,0) AS \'VAR08\', ',
			' IFNULL(VAR09.VAR09,0) AS \'VAR09\', ',
			' IFNULL(VAR13a.VAR13a,0) AS \'VAR13a\', ',
			' IFNULL(VAR13b.VAR13b,0) AS \'VAR13b\', ',
			' IFNULL(VAR13c.VAR13c,0) AS \'VAR13c\', ',
			' IFNULL(VAR16.VAR16,0) AS \'VAR16\', ',
			' IFNULL(VAR18.VAR18,0) AS \'VAR18\', ',
			' IFNULL(VAR19.VAR19,0) AS \'VAR19\', ',
			' IFNULL(VAR20.VAR20,0) AS \'VAR20\', ',
			' IFNULL(VAR21.VAR21,0) AS \'VAR21\', ',
			' IFNULL(VAR22.VAR22,0) AS \'VAR22\', ',
			' IFNULL(VAR23.VAR23,0) AS \'VAR23\', ',
			' IFNULL(VAR27.VAR27,0) AS \'VAR27\', ',
			' IFNULL(VAR28.VAR28,0) AS \'VAR28\', ',
			' IFNULL(VAR31.VAR31,0) AS \'VAR31\' ',
			' FROM ' ,
			' (SELECT * FROM ', @base,') AS ', @base,' ' ,
			' LEFT OUTER JOIN ' ,
				' (SELECT b.disciplina_id, b.aluno_id, count(*) AS \'VAR01\' ',
				' FROM mdl_forum_posts p ' ,
				' INNER JOIN mdl_forum_discussions d ON d.id = p.discussion ',
				' INNER JOIN ', @base,' b ON d.course=b.disciplina_id AND p.userid=b.aluno_id AND p.created BETWEEN b.data_inicio and b.data_fim ',
				' GROUP BY b.disciplina_id, b.aluno_id) AS VAR01 ',
				' ON VAR01.disciplina_id = ', @base,'.disciplina_id AND VAR01.aluno_id = ', @base,'.aluno_id ' ,
			' LEFT OUTER JOIN ',
				' (SELECT b.disciplina_id, b.aluno_id, count(*) AS \'VAR04\' ' ,
				' FROM mdl_message_read r ',
				' INNER JOIN ', @base,' b ON b.aluno_id=r.useridfrom AND r.timecreated BETWEEN b.data_inicio and b.data_fim ',
				' GROUP BY b.disciplina_id, b.aluno_id) AS VAR04 ',
				' ON VAR04.disciplina_id = ', @base,'.disciplina_id AND VAR04.aluno_id = ', @base,'.aluno_id ' ,
			' LEFT OUTER JOIN ',
				' (SELECT b.disciplina_id, b.aluno_id, count(*) AS \'VAR05\' ' ,
				' FROM mdl_message_read r ',
				' INNER JOIN ', @base,' b ON b.aluno_id=r.useridto AND r.timecreated BETWEEN b.data_inicio and b.data_fim ',
				' GROUP BY b.disciplina_id, b.aluno_id) AS VAR05 ',
				' ON VAR05.disciplina_id = ', @base,'.disciplina_id AND VAR05.aluno_id = ', @base,'.aluno_id '	,
			' LEFT OUTER JOIN ',
				' (SELECT temp.disciplina_id, count(*) AS \'VAR08\' ' ,
				' FROM (SELECT b.disciplina_id,module,cmid, count(*) ' ,
				' FROM (SELECT distinct(disciplina_id), data_inicio, data_fim FROM ', @base,') b ' ,
				' INNER JOIN (SELECT * FROM ', @view_base_log_reduzido, ' WHERE cmid IS NOT NULL AND ',
				' (module=\'resource\' OR ',
				' module=\'folder\' OR ',
				' module=\'url\' OR ',
				' module=\'page\' OR ',
				' module=\'book\')) l ',
				' ON b.disciplina_id=l.course AND l.time BETWEEN b.data_inicio and b.data_fim ',
				' GROUP BY b.disciplina_id,l.module,cmid) AS temp ',
				' GROUP BY temp.disciplina_id) AS VAR08 ',
				' ON VAR08.disciplina_id = ', @base,'.disciplina_id ' ,
			' LEFT OUTER JOIN ',
				' (SELECT temp.disciplina_id, count(*) AS \'VAR09\' ' ,
				' FROM (SELECT b.disciplina_id,module,cmid, count(*) ' ,
				' FROM (SELECT distinct(disciplina_id), data_inicio, data_fim FROM ', @base,') b ' ,
				' INNER JOIN (SELECT * FROM ', @view_base_log_reduzido, ' WHERE cmid IS NOT NULL AND /*Atividades*/(module=\'assign\' OR module=\'forum\' OR module=\'quiz\')) l ',
				' ON b.disciplina_id=l.course AND l.time BETWEEN b.data_inicio and b.data_fim ',
				' GROUP BY b.disciplina_id,l.module,cmid) AS temp ',
				' GROUP BY temp.disciplina_id) AS VAR09 ',
				' ON VAR09.disciplina_id = ', @base,'.disciplina_id ' ,
			' LEFT OUTER JOIN ',
				' (SELECT b.disciplina_id,b.aluno_id, count(*) AS \'VAR13a\' ',
				' FROM ', @base,' b ' ,
				' INNER JOIN (SELECT * FROM ', @view_base_log_reduzido, ' WHERE action=\'login\' AND HOUR(FROM_UNIXTIME(time)) >= 6 AND HOUR(FROM_UNIXTIME(time)) < 12) l ',
				' ON b.aluno_id=l.userid AND l.time BETWEEN b.data_inicio and b.data_fim ',
				' GROUP BY b.disciplina_id,b.aluno_id) AS VAR13a ',
				' ON  VAR13a.aluno_id = ', @base,'.aluno_id AND VAR13a.disciplina_id = ', @base,'.disciplina_id ' ,
			' LEFT OUTER JOIN ',
				' (SELECT b.disciplina_id,b.aluno_id, count(*) AS \'VAR13b\' ',
				' FROM ', @base,' b ' ,
				' INNER JOIN (SELECT * FROM ', @view_base_log_reduzido, ' WHERE action=\'login\' AND HOUR(FROM_UNIXTIME(time)) >= 12 AND HOUR(FROM_UNIXTIME(time)) < 18) l ',
				' ON b.aluno_id=l.userid AND l.time BETWEEN b.data_inicio and b.data_fim ',
				' GROUP BY b.disciplina_id,b.aluno_id) AS VAR13b ',
				' ON  VAR13b.aluno_id = ', @base,'.aluno_id AND VAR13b.disciplina_id = ', @base,'.disciplina_id ',
			' LEFT OUTER JOIN ',
				' (SELECT b.disciplina_id,b.aluno_id, count(*) AS \'VAR13c\' ',
				' FROM ', @base,' b ' ,
				' INNER JOIN (SELECT * FROM ', @view_base_log_reduzido, ' WHERE action=\'login\' AND HOUR(FROM_UNIXTIME(time)) >= 18 AND HOUR(FROM_UNIXTIME(time)) < 24) l ',
				' ON b.aluno_id=l.userid AND l.time BETWEEN b.data_inicio and b.data_fim ',
				' GROUP BY b.disciplina_id,b.aluno_id) AS VAR13c ',
				' ON  VAR13c.aluno_id = ', @base,'.aluno_id AND VAR13c.disciplina_id = ', @base,'.disciplina_id ',
			' LEFT OUTER JOIN ',
				' (SELECT temp.disciplina_id, temp.aluno_id, count(*) AS \'VAR16\' ',
				' FROM (SELECT b.disciplina_id, b.aluno_id, r.useridto, count(*) AS \'VAR16_temp\' ',
				' FROM mdl_message_read r ',
				' INNER JOIN ', @base, ' b ON b.aluno_id=r.useridfrom AND r.timecreated BETWEEN b.data_inicio and b.data_fim ',
				' INNER JOIN ', @view_alunos, ' a ON a.aluno_id=r.useridto AND a.disciplina_id=b.disciplina_id ',
				' GROUP BY b.disciplina_id, b.aluno_id,r.useridto) AS temp ',
				' GROUP BY temp.disciplina_id, temp.aluno_id) AS VAR16 ',
				' ON VAR16.disciplina_id = ', @base, '.disciplina_id AND VAR16.aluno_id = ', @base,'.aluno_id ',
			' LEFT OUTER JOIN ',
				' (SELECT b.disciplina_id,b.aluno_id, count(*) AS \'VAR18\' ',
				' FROM ', @base,' b ' ,
				' INNER JOIN (SELECT * FROM ', @view_base_log_reduzido, ' WHERE action=\'login\') l ',
				' ON b.aluno_id=l.userid AND l.time BETWEEN b.data_inicio and b.data_fim ',
				' GROUP BY b.disciplina_id,b.aluno_id) AS VAR18 ',
				' ON  VAR18.aluno_id = ', @base,'.aluno_id AND VAR18.disciplina_id = ', @base,'.disciplina_id ' ,
			' LEFT OUTER JOIN ',
				' (SELECT b.disciplina_id, b.aluno_id, count(*) AS \'VAR19\' ' ,
				' FROM mdl_message_read r ',
				' INNER JOIN ', @base,' b ON b.aluno_id=r.useridfrom AND r.timecreated BETWEEN b.data_inicio and b.data_fim ',
				' INNER JOIN ', @view_professores, ' p ON p.professor_id=r.useridto AND p.disciplina_id=b.disciplina_id ',
				' GROUP BY b.disciplina_id, b.aluno_id) AS VAR19 ',
				' ON VAR19.disciplina_id = ', @base,'.disciplina_id AND VAR19.aluno_id = ', @base,'.aluno_id ',
			' LEFT OUTER JOIN ',
				' (SELECT b.disciplina_id, b.aluno_id, count(*) AS \'VAR20\' ',
				' FROM mdl_message_read r ',
				' INNER JOIN ', @base, ' b ON b.aluno_id=r.useridto AND r.timecreated BETWEEN b.data_inicio and b.data_fim ',
				' INNER JOIN ', @view_professores, ' p ON p.professor_id=r.useridfrom AND p.disciplina_id=b.disciplina_id ',
				' GROUP BY b.disciplina_id, b.aluno_id) AS VAR20 ',
				' ON VAR20.disciplina_id = ', @base,'.disciplina_id AND VAR20.aluno_id = ', @base,'.aluno_id ',
			' LEFT OUTER JOIN ',
				' (SELECT b.disciplina_id, b.aluno_id, count(*) AS \'VAR21\' ' ,
				' FROM mdl_message_read r ',
				' INNER JOIN ', @base,' b ON b.aluno_id=r.useridto AND r.timecreated BETWEEN b.data_inicio and b.data_fim ',
				' INNER JOIN ', @view_alunos, ' a ON a.aluno_id=r.useridfrom AND a.disciplina_id=b.disciplina_id ',
				' GROUP BY b.disciplina_id, b.aluno_id) AS VAR21 ',
				' ON VAR21.disciplina_id = ', @base,'.disciplina_id AND VAR21.aluno_id = ', @base,'.aluno_id ' ,
			' LEFT OUTER JOIN ',
				' (SELECT b.disciplina_id, b.aluno_id, count(*) AS \'VAR22\' ' ,
				' FROM mdl_message_read r ',
				' INNER JOIN ', @base,' b ON b.aluno_id=r.useridfrom AND r.timecreated BETWEEN b.data_inicio and b.data_fim ',
				' INNER JOIN ', @view_alunos, ' a ON a.aluno_id=r.useridto AND a.disciplina_id=b.disciplina_id ',
				' GROUP BY b.disciplina_id, b.aluno_id) AS VAR22 ',
				' ON VAR22.disciplina_id = ', @base,'.disciplina_id AND VAR22.aluno_id = ', @base,'.aluno_id ' ,
			' LEFT OUTER JOIN ',
				' (SELECT b.disciplina_id, count(*) AS \'VAR23\' ' ,
				' FROM mdl_assign a ',
				' INNER JOIN (SELECT distinct(disciplina_id),data_inicio,data_fim  FROM ', @base,') b ' ,
				' ON b.disciplina_id=a.course AND a.duedate BETWEEN b.data_inicio and b.data_fim ',
				' GROUP BY b.disciplina_id) AS VAR23 ',
				' ON VAR23.disciplina_id = ', @base,'.disciplina_id ' ,
			' LEFT OUTER JOIN ',
				' (SELECT temp.disciplina_id,temp.aluno_id, AVG(temp.Acesso_Objeto) AS \'VAR27\' ' ,
				' FROM (SELECT b.disciplina_id,b.aluno_id, module,cmid, count(*) AS \'Acesso_Objeto\' ',
				' FROM ', @base,' b ' ,
				' INNER JOIN (SELECT * FROM ', @view_base_log_reduzido, ' WHERE cmid IS NOT NULL AND ' ,
					' (module=\'assign\' AND action=\'view\') OR ' ,
					' action=\'view forum\' OR ',
					' (module=\'assignment\' AND action=\'view\') OR ',
					' (module=\'choice\' AND action=\'view\') OR ',
					' (module=\'feedback\' AND action=\'view\') OR ',
					' (module=\'survey\' AND action=\'view\') OR '
					' (module=\'chat\' AND action=\'view\') OR '
					' (module=\'quiz\' AND action=\'view\')) l ',
				' ON b.disciplina_id=l.course AND b.aluno_id=l.userid AND l.time BETWEEN b.data_inicio and b.data_fim ',
				' GROUP BY b.disciplina_id,b.aluno_id,l.module,cmid) AS temp ',
				' GROUP BY temp.disciplina_id, temp.aluno_id) AS VAR27 ',
				' ON VAR27.disciplina_id = ', @base,'.disciplina_id AND VAR27.aluno_id = ', @base,'.aluno_id '		,
			' LEFT OUTER JOIN ',
				' (SELECT temp.disciplina_id, count(*) AS \'VAR28\' FROM ',
				' (SELECT distinct b.disciplina_id,f.id, f.course ' ,
				' FROM mdl_forum f ' ,
				' INNER JOIN mdl_forum_discussions d ON f.id=d.forum ',
				' INNER JOIN mdl_forum_posts p ON d.id=p.discussion ',
				' INNER JOIN (SELECT distinct(disciplina_id),data_inicio,data_fim FROM ', @base,') b ',
				' ON b.disciplina_id=f.course AND p.created BETWEEN b.data_inicio and b.data_fim ' ,
				' ) temp ',
				' GROUP BY temp.disciplina_id) AS VAR28 ',
				' ON VAR28.disciplina_id = ', @base,'.disciplina_id ' ,
			' LEFT OUTER JOIN ',
				' (SELECT b.disciplina_id,b.aluno_id, count(*) AS \'VAR31\' ',
				' FROM ', @base,' b ' ,
				' INNER JOIN (SELECT * FROM ', @view_base_log_reduzido, ' WHERE action=\'view forum\') l ',
				' ON b.aluno_id=l.userid AND b.disciplina_id=l.course AND l.time BETWEEN b.data_inicio and b.data_fim ',
				' GROUP BY b.disciplina_id,b.aluno_id) AS VAR31 ',
				' ON  VAR31.aluno_id = ', @base,'.aluno_id AND VAR31.disciplina_id = ', @base,'.disciplina_id ' ,
			' ORDER BY ' ,
				' ', @base,'.curso, ', @base,'.semestre, ', @base,'.periodo, ', @base,'.disciplina_nome, ', @base,'.aluno_nome; '
	);

	PREPARE stmt FROM @query;
	EXECUTE stmt;
	DEALLOCATE PREPARE stmt;

END //
DELIMITER ;
