DELIMITER //
DROP FUNCTION IF EXISTS HANDLE_SEMESTER//
CREATE FUNCTION HANDLE_SEMESTER(semester VARCHAR(255)) RETURNS VARCHAR(255) DETERMINISTIC
BEGIN
	return RIGHT(DELETE_INNER_SPACES(LCASE(semester)), 6);
END//
DELIMITER ;
