DELIMITER //
DROP FUNCTION IF EXISTS DELETE_DOUBLE_SPACES//
CREATE FUNCTION DELETE_DOUBLE_SPACES(str VARCHAR(255)) RETURNS VARCHAR(255) DETERMINISTIC
BEGIN
 while instr(str, '  ') > 0 do
 set str = replace(str, '  ', ' ');
 end while;
 return trim(str);
END//
DELIMITER ;
